### ISSUE TITLE
Add ability to always exclude the addons directory

### ISSUE THREAD

**Issue by BCD-qed** [MakovWait/godot-find-everywhere#2]
***Great plugin!*** 
I would appreciated a quality of life option to exclude the addons directory. Perhaps a checkbox or a configurable exclude list? 
I realize that exclusion can be accomplished with REGEX, but I will end up adding it all the time.
Thank you for sharing your plugin

**Comment by MakovWait** [comment]
Hey. Now the feature is in `main`.  I will submit it to Asset Library in a few days. 
Here is a snippet from README about how to use the feature:

Folders to exclude are able to be configured via <code>Editor Settings/Addons/Find Everywhere</code>
List folders you want to ignore joined with `,` i.e. `res://addons,res://trash`. Also the _full_ path to folder is expected (started with `res://`).
